- hosts: me
  gather_facts: no

  vars:
    nginx_max_conns: 30
    nginx_http_port: 80
    nginx_client_max_body_size: 1M

    app_path: /home/{{ ansible_user }}/my-project
    app_http_port: 8090

  remote_user: '{{ ansible_user }}'

  handlers:
  pre_tasks:
  roles:

  tasks:
    - name: checkout app from git repo
      git:
        repo: "https://github.com/michondr/my-project"
        dest: '{{ app_path }}'
        clone: yes
        accept_hostkey: yes
        update: yes
        version: master

    - name: run composer install
      shell: cd {{ app_path }} && composer install

    - name: run composer install
      shell: cd {{ app_path }} && bin/console cache:clear

  post_tasks: