- hosts: time_table_tweak
  gather_facts: no

  vars:
    project_folder: my-project
    app_path: /home/{{ ansible_user }}/{{ project_folder }}

  remote_user: '{{ ansible_user }}'

  handlers:
  pre_tasks:
  roles:

  tasks:
    - name: checkout app from git repo
      git:
        repo: "https://github.com/michondr/my-project"
        dest: '{{ app_path }}'
        clone: yes
        force: yes
        accept_hostkey: yes
        update: yes
        version: "{{ branch | default('master') }}"

    - name: set .env to project
      shell: cp /home/{{ ansible_user }}/.time_table_tweak_env {{ app_path }}/.env

    - name: delete composer folder
      file:
        path: /home/{{ ansible_user }}/.composer
        state: absent
      become: yes

    - name: run composer install
      shell: composer install --working-dir {{ app_path }}

    - name: managed folders has 777 chmod.
      file:
        path: "{{ app_path }}/{{ item }}"
        mode: 0777
        recurse: true
      with_items:
        - var/cache
        - var/log

  post_tasks: