- hosts: time_table_tweak
  gather_facts: no

  vars:
    project_folder: my-project
    app_path: /home/{{ ansible_user }}/{{ project_folder }}
    nxinx_host: time-table-tweak

  vars_prompt:
    - name: "symfony_env"
      prompt: "application enviroment"
      default: "prod"

    - name: "db_host"
      prompt: "database host"
      default: "127.0.0.1"

    - name: "db_port"
      prompt: "database port"
      default: "3306"

    - name: "db_name"
      prompt: "database name"
      default: "time_table_tweak"

    - name: "db_user"
      prompt: "database user"
      default: "root"

    - name: "db_pass"
      prompt: "database password"
      default: "root"

    - name: "sentry_dns"
      prompt: "sentry dns"
      default: "https://f1228f06faee4b5a8c7ea7cb3c965be9:21f82bc3901941938096cb1ac9c37e26@sentry.io/1198135"

  remote_user: '{{ ansible_user }}'

  pre_tasks:
    - name: test connection
      ping:

    - name: Add Ondrej Sury's apt key
      become: yes
      apt_key:
        url: 'https://packages.sury.org/php/apt.gpg'
        state: present

    - name: Add repository for PHP 7.2
      become: yes
      apt_repository: repo='ppa:ondrej/php'

  tasks:
    - name: install packages
      become: true
      apt: name={{ item }}
      with_items:
        - php7.2
        - php7.2-fpm
        - php7.2-curl
        - php7.2-xml
        - php7.2-zip
        - php7.2-mysql
        - nginx
        - git
        - htop

    - name: install latest composer
      become: yes
      shell: "{{ item }}"
      with_items:
        - 'curl -sS https://getcomposer.org/installer -o ~/composer-setup.php'
        - 'php ~/composer-setup.php --install-dir=/usr/bin --filename=composer'
        - 'rm ~/composer-setup.php'

    - name: add nginx config to /etc/nginx/sites-enabled/
      become: true
      template:
        src: 'templates/time_table_tweak_nginx'
        dest: '/etc/nginx/sites-enabled/time_table_tweak'

    - name: add .env config to ~/
      template:
        src: 'templates/time_table_tweak_env'
        dest: '/home/{{ ansible_user }}/.time_table_tweak_env'

    - name: fix locale
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: "{{ item }}"
      with_items:
        - export LC_ALL=en_US.UTF-8
        - export LANG=en_US.UTF-8
        - export LANGUAGE=en_US.UTF-8

  post_tasks:
    - name: restarting services
      become: true
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - php7.2-fpm
